MA-22692 Remove "camera.device-external-imx-impl" in camera hal by default
Since in MA-19953 the build script will add this dependency to build
dependency, so remove it from default Android.bp.

This patch will fix non-NXP project build error:
error: hardware/interfaces/camera/provider/default/Android.bp:49:1:
module "android.hardware.camera.provider-V1-external-impl" variant
"android_vendor_arm64_armv8-a_cortex-a53_shared": depends on disabled
module "camera.device-external-imx-impl"

Change-Id: I68a6ad1ecb93a374e4e0b04bbe1ffc8319d13aaf
Signed-off-by: Haoran Wang <elven.wang@nxp.com>
Reviewed-on: http://androidsource.nxp.com/project/25446
Reviewed-by: Xuegang Liu <xuegang.liu@nxp.com>
(cherry picked from commit c91dd419b7c7adcfbb1fbc9a7b95c29217aa6c54)
Reviewed-on: http://androidsource.nxp.com/project/25904